### ISSUE TITLE
R.A.F

### ISSUE THREAD

**Issue by guiadco** [ccl-consulting/freshdesk-openapi-definitions#1]
## Done

- [x] /settings/helpdesk
  - [x] `GET`
- [x] /sla_policies
  - [x] `GET`
- [x]  scenario_automations.json
  - [x] `GET`
- [x] /business_hours
  - [x] `GET`
- [x] /business_hours/{businesshoursID}
  - [x] `GET`
- [x] /products
  - [x] `GET`
- [x] /products/{productID}
  - [x] `GET`
- [x] /email/settings
  - [x] `GET`
- [x] /email/mailboxes
  - [x] `GET`
- [x] /email_configs
  - [x] `GET`
- [x] /email_configs/{emailID}
  - [x] `GET`
- [x] /surveys/satisfaction_ratings
  - [x] `GET`
- [x] /surveys
  - [x] `GET`
- [x] /solutions/categories
  - [x] `GET`
- [x] /discussions/categories
  - [x] `GET`
- [x] /canned_response_folders
  - [x] `GET`
- [x] /company_fields
  - [x] `GET`
- [x] /companies
  - [x] `GET`
- [x] /admin/groups
  - [x] `GET`
- [x] /groups
  - [x] `GET`
- [x] /skills
  - [x] `GET`
- [x] /agents
  - [x] `GET`
- [x] /jobs/{jobID}
  - [x] `GET`
- [x] /account
  - [x] `GET`
- [x] /ticket-forms
  - [x] `GET`
- [x] /ticket_fields
  - [x] `GET`
- [x] /tickets
  - [x] `GET`
- [x] /time_entries/{timeID}/toggle_timer
  - [x] `GET`
- [x] /time_entries/{timeID}
  - [x] `DELETE`
  - [x] `PUT`
- [x] /tickets/{ticketID}/time_entries
  - [x]  `POST`
- [x] /time_entries
  - [x]  `GET`
- [x] /contact_fields
  - [x]  `GET`
- [x] /contacts
  - [x]  `GET` 

## Resources Done
- [x] Roles

## Verbs
- `delete` done for all

## TODO
- Export Account: https://developers.freshdesk.com/api/#generate_export
